- name: Install & configure Caddy
  hosts: athelas
  become: true
  tasks:

  - name: Add Caddy GPG Key
    ansible.builtin.get_url:
      url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
      dest: /etc/apt/keyrings/caddy.asc
      mode: '0644'
      force: true

  - name: Add Caddy Repo
    ansible.builtin.apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
      state: present

  - name: Add Caddy Src Repo
    ansible.builtin.apt_repository:
      repo: deb-src [signed-by=/etc/apt/keyrings/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
      state: present

  - name: Install Caddy
    ansible.builtin.package:
      name: caddy

  - name: Creating webserver root folder
    ansible.builtin.file:
      path: /var/www/html/
      state: directory
      group: caddy
      owner: caddy

  - name: Creating webserver index.html
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: touch
      group: caddy
      owner: caddy

  - name: Editing Caddyfile
    ansible.builtin.template:
      src: ~/ansible/templates/Caddyfile.j2
      dest: /etc/caddy/Caddyfile

  - name: Reboot
    ansible.builtin.reboot:
