---
# tasks file for setup_iptables
- name: Open needed ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    in_interface: eth0
    jump: ACCEPT
    destination_ports:
      - "22"
      - "443"
      - "80"

- name: Set INPUT policy to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP

- name: Create iptables folder in /etc
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: '0755'

- name: Install iptables-persistent for rules persistence
  ansible.builtin.package:
    name: iptables-persistent
    update_cache: true

- name: Save IPv4 rules to keep them on reboot
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v4

- name: Save IPv6 rules to keep them on reboot
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/rules.v6